---
dependencies: []

galaxy_info:
  author: Dominik Lenhardt <dominik@lenhardt-it.com>
  company: Dominik Lenhardt IT-Services
  description: Install and configure MariaDB server
  galaxy_tags:
  - claranet
  - mariadb
  license: MIT
  min_ansible_version: '2.10'
  namespace: lenmail
  platforms:
  - name: EL
    versions:
    - all
  - name: Amazon
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  role_name: mariadb
